class ArticlesController < ApplicationController
  # Generated by `bin/rails generate controller Articles index --skip-routes`
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end
